import os
import re
import argparse
import cv2
import numpy as np
from tqdm import tqdm
from PIL import Image
import torch
import torchvision
import torch.nn.functional as F

from segment_anything import SamAutomaticMaskGenerator, sam_model_registry, SamPredictor
from ram.models import ram_plus
from ram import inference_ram as ram_inference
from ram import get_transform
from GroundingDINO.groundingdino.util.inference import Model

from utils_image.image_extract import get_seg_img, pad_img, sam_predictor, update_seg_images_from_seg_maps
from utils_image.clip_embed import OpenCLIPNetwork, OpenCLIPNetworkConfig

def sam_encoder(mask_generator, image):

    masks = mask_generator.generate(image)

    def mask2segmap(masks, image):
        seg_img_list = []
        seg_map = -np.ones(image.shape[:2], dtype=np.int32)
        
        for i in range(len(masks)):
            mask = masks[i]
            seg_img = get_seg_img(mask, image)
            if seg_img.shape[0] == 0 or seg_img.shape[1] == 0:
                continue
            pad_seg_img = cv2.resize(pad_img(seg_img), (224,224))
            seg_img_list.append(pad_seg_img)

            seg_map[masks[i]['segmentation']] = i
        seg_imgs = np.stack(seg_img_list, axis=0) # b,H,W,3
        seg_imgs = (torch.from_numpy(seg_imgs.astype("float32")).permute(0,3,1,2) / 255.0).to('cuda')

        return seg_imgs, seg_map
    
    seg_images, seg_maps = {}, {}
    if len(masks) > 0:
        seg_images['default'], seg_maps['default'] = mask2segmap(masks, image)
    else:
        assert False, "No masks generated by SAM_hq"

    return seg_images, seg_maps

def embed_img(image_path, sam_encoder, sam_predictor, detections):
    
    image_pil = Image.open(image_path).convert("RGB")
    image = cv2.imread(image_path)
 
    seg_images, seg_map = sam_encoder(mask_generator, np.array(image_pil))
    match_indices, seg_map_update, seg_masks, _= sam_predictor(args, predictor_sam, seg_map, image, detections)  
    seg_images, bbox_images = update_seg_images_from_seg_maps(seg_map_update, image)
    
    clip_embeds = {}
    for mode in ['default']:
        seg_tiles = seg_images[mode].to("cuda")
        bbox_tiles = bbox_images[mode].to("cuda")
        
        with torch.no_grad():
            f_mask = clip_model.encode_image(seg_tiles)
            f_mask = f_mask / f_mask.norm(dim=-1, keepdim=True)
            f_box = clip_model.encode_image(bbox_tiles)
            f_box = f_box / f_box.norm(dim=-1, keepdim=True)
            clip_embed = 0.8 * f_mask + 0.2 * f_box
        
        clip_embed /= clip_embed.norm(dim=-1, keepdim=True)
        clip_embeds[mode] = clip_embed.detach().cpu().half()

    return clip_embeds, seg_map_update

def trailing_number(fname):
    m = re.search(r'(\d+)', fname)
    return int(m.group(1)) if m else -1

def create(args, img_folder, save_folder, vis_folder):
    data_list = os.listdir(img_folder)
    data_list = sorted(data_list, key=trailing_number)
    #selected_list = [f for f in data_list if trailing_number(f) % 10 == 0]

    assert len(data_list) is not None, "image_list must be provided to generate features"
    embed_size=512
    seg_maps = []
    total_lengths = []
    timer = 0
    img_embeds = torch.zeros((len(data_list), 100, embed_size))
    seg_maps = torch.zeros((len(data_list), 1, 680, 1200)) 
    mask_generator.predictor.model.to(args.device)

    for i, data_path in tqdm(list(enumerate(data_list)), desc="Embedding images", leave=False):
        timer += 1
        torch.cuda.empty_cache()
        image_path = os.path.join(img_folder, data_path)
      
        image_pil = Image.open(image_path).convert("RGB")
        image = cv2.imread(image_path)

        with torch.no_grad():
            transform = get_transform(image_size = args.image_size)
            ram_model = ram_plus(pretrained = args.ram_ckpt, image_size = args.image_size, vit = 'swin_l')
            ram_model.eval()
            ram_model = ram_model.to(args.device)
            image_pil_ram = transform(image_pil).unsqueeze(0).to(args.device)
            res = ram_inference(image_pil_ram, ram_model)
            classes = [item.strip() for item in res[0].split("|")]
            remove_set = {'classroom', 'room', 'library', 'blue', 'green', 'brown', 'writing', 'office', 
                          'bathroom', 'bedroom', 'corner', 'doorway', 'white', 'kitchen', 'dormitory', 
                          'hallway', 'lead to', 'living room', 'restroom', 'photo', 'dining room', 'home appliance', 
                          'bunk bed', 'entertainment center', 'meeting room', 'dark', 'waiting room', 'office building'} 
            classes = [c for c in classes if c not in remove_set]
            classes = list(set(classes))  
            detections = grounding_dino_model.predict_with_classes(
                image=image, 
                classes=classes,
                box_threshold=args.box_threshold,
                text_threshold=args.text_threshold,
            )
            
            nms_idx = torchvision.ops.nms(
                torch.from_numpy(detections.xyxy), 
                torch.from_numpy(detections.confidence), 
                args.nms_threshold
            ).numpy().tolist()

            detections.xyxy = detections.xyxy[nms_idx]
            detections.confidence = detections.confidence[nms_idx]
            detections.class_id = detections.class_id[nms_idx]
            
            valid_idx = (detections.class_id != -1) & (detections.class_id != None)
            detections.xyxy = detections.xyxy[valid_idx]
            detections.confidence = detections.confidence[valid_idx]
            detections.class_id = detections.class_id[valid_idx]

            H, W = image.shape[:2]
            image_area = H * W

            xyxy = detections.xyxy
            box_area = (xyxy[:, 2] - xyxy[:, 0]) * (xyxy[:, 3] - xyxy[:, 1])

            valid_idx_area = box_area < 0.8 * image_area

            detections.xyxy = detections.xyxy[valid_idx_area]
            detections.confidence = detections.confidence[valid_idx_area]
            detections.class_id = detections.class_id[valid_idx_area]
        
        img_embed, seg_map = embed_img(image_path, sam_encoder, sam_predictor, detections)
       
        lengths = [len(v) for k, v in img_embed.items()]
        total_length = sum(lengths)
        total_lengths.append(total_length)

        if total_length > img_embeds.shape[1]:
            pad = total_length - img_embeds.shape[1]
            img_embeds = torch.cat([
                img_embeds,
                torch.zeros((len(data_list), pad, embed_size))
            ], dim=1)

        img_embed = torch.cat([v for k, v in img_embed.items()], dim=0)
        assert img_embed.shape[0] == total_length
      
        img_embeds[i, :total_length] = img_embed
        seg_map_tensor = []
        lengths_cumsum = lengths.copy()
        for j in range(1, len(lengths)):
            lengths_cumsum[j] += lengths_cumsum[j-1]
        for j, (k, v) in enumerate(seg_map.items()):
            if j == 0:
                seg_map_tensor.append(torch.from_numpy(v))
                continue
            assert v.max() == lengths[j] - 1, f"{j}, {v.max()}, {lengths[j]-1}"
            v[v != -1] += lengths_cumsum[j-1]
            seg_map_tensor.append(torch.from_numpy(v))
        seg_map = torch.stack(seg_map_tensor, dim=0)
        seg_maps[i] = seg_map
      
        save_path = os.path.join(save_folder, os.path.splitext(os.path.basename(image_path))[0])
        curr = {
            'feature': img_embeds[i, :total_lengths[i]],
            'seg_maps': seg_maps[i],
        }

        sava_numpy(save_path, curr)
    
def sava_numpy(save_path, data):
    save_path_s = save_path + '_s.npy'
    save_path_f = save_path + '_f.npy'
    np.save(save_path_s, data['seg_maps'].numpy())
    np.save(save_path_f, data['feature'].numpy())

if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--sam_model_type', default="vit_h")
    parser.add_argument('--sam_ckpt', default="./segment_anything/ckpt/sam_vit_h_4b8939.pth")
    parser.add_argument('--ram_ckpt', type=str, default="./ram/ram_plus_swin_large_14m.pth")
    parser.add_argument('--gsa_config', default="./GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py")
    parser.add_argument('--gsa_ckpt', type=str, default="./GroundingDINO/groundingdino_swint_ogc.pth")
    parser.add_argument('--image_size', type=int, default=384)
    parser.add_argument("--box_threshold", type=float, default=0.3)
    parser.add_argument("--text_threshold", type=float, default=0.3)
    parser.add_argument("--nms_threshold", type=float, default=0.3)
    parser.add_argument('--dataset_path', type=str, default="scene0000")
    parser.add_argument('--resolution', type=int, default=-1)
    parser.add_argument('--device', type=str, default="cuda:0")
    args = parser.parse_args()
    torch.set_default_dtype(torch.float32)

    dataset_path = args.dataset_path

    if os.path.exists(os.path.join(dataset_path, 'color')):
        img_folder = os.path.join(dataset_path, 'color')
    elif os.path.exists(os.path.join(dataset_path, 'images')):
        img_folder = os.path.join(dataset_path, 'images')
    else:
        raise ValueError('Image folder not found')

    clip_model = OpenCLIPNetwork(args, OpenCLIPNetworkConfig)
    grounding_dino_model = Model(model_config_path=args.gsa_config, model_checkpoint_path=args.gsa_ckpt, device=args.device)
    sam = sam_model_registry[args.sam_model_type](checkpoint=args.sam_ckpt)
    sam.to(device=args.device)
    mask_generator = SamAutomaticMaskGenerator(model=sam, 
                                            points_per_side=16,
                                            pred_iou_thresh=0.8,
                                            box_nms_thresh=0.7,
                                            stability_score_thresh=0.95,
                                            crop_n_layers=1,
                                            crop_n_points_downscale_factor=1,
                                            min_mask_region_area=100,)
    predictor_sam = SamPredictor(sam_model=sam)

    save_folder = os.path.join(dataset_path, 'language_features')
    vis_folder = os.path.join(dataset_path, 'vis_seg')
    os.makedirs(save_folder, exist_ok=True)
    os.makedirs(vis_folder, exist_ok=True)
    create(args, img_folder, save_folder, vis_folder)